Update pgadmin

diff --git a/pgadmin b/pgadmin
--- a/pgadmin
+++ b/pgadmin
@@ -1,2 +1,109 @@
-TASK [service-role : Fetch artifact version from maven-metadata.xml] ***********
-fatal: [182.2.29.25]: FAILED! => {"changed": true, "cmd": ["curl", "-s", "https://host/nexus-arc/repository/sgcib-sgabs-maven2-hosted-snapshots/com/socgen/unibank/services/unibank-service-branch-onboarding/1.9.0-SNAPSHOT/maven-metadata.xml", "|", "grep", "-A", "1", "<extension>jar</extension>", "|", "grep", "<value>", "|", "sed", "-E", "s/.*<value>(.*)<\\/value>.*/\\1/", "|", "grep", "-A", "1", "<extension>jar</extension>", "|", "grep", "<value>", "|", "sed", "-E", "s/.*<value>(.*)<\\/value>.*/\\1/"], "delta": "0:00:00.049705", "end": "2025-01-07 11:30:37.718277", "msg": "non-zero return code", "rc": 6, "start": "2025-01-07 11:30:37.668572", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
+#!/bin/bash
+
+STRIGIL_DIR="/home/app/work/strigil"
+LOG_FILE="$STRIGIL_DIR/cron_logs/cron_log_$(date +'%Y-%m-%d').log"
+CRITICAL_USAGE=75
+FILESYSTEM="/dev/mapper/vg0-root"
+SMTP_HOST="{{ smtp_host }}"
+SMTP_PORT=25
+CONFIG_FILE="$STRIGIL_DIR/strigil_config.json"
+START_TIME=$(date)
+
+# Extract hostname and nickname
+NICKNAME=$(echo "$PLT_VM_NICKNAME")
+HOSTNAME=$(echo "$HOSTNAME")
+
+# Construct email address
+MAIL_FROM="${HOSTNAME}_${NICKNAME}@socgen.com"
+MAIL_TO="anouar.harrou@socgen.com"
+
+# Helper function to send email notifications
+send_email() {
+    local subject=$1
+    local message=$2
+    local temp_file=$(mktemp)
+
+    echo -e "Subject: $subject\n\n$message" > "$temp_file"
+
+    curl -s --url "smtp://$SMTP_HOST:$SMTP_PORT" \
+         --mail-from "$MAIL_FROM" \
+         --mail-rcpt "$MAIL_TO" \
+         --upload-file "$temp_file"
+
+    rm -f "$temp_file"
+}
+
+# Create log directory and file if they don't exist
+mkdir -p "$(dirname "$LOG_FILE")" || {
+    send_email "Script Failure: Log Directory Creation Failed" "Failed to create log directory."
+    exit 1
+}
+touch "$LOG_FILE" || {
+    send_email "Script Failure: Log File Creation Failed" "Failed to create log file."
+    exit 1
+}
+
+{
+    echo "#######################################################################"
+    echo "CRON JOB STARTED AT $START_TIME"
+    echo "#######################################################################"
+    echo "CHECK DISK USAGE"
+
+    usage=$(df -h | awk -v fs="$FILESYSTEM" '$1 == fs {print $5}' | sed 's/%//')
+    echo "FILESYSTEM $FILESYSTEM USAGE : $usage%"
+
+    if [ "$usage" -ge "$CRITICAL_USAGE" ]; then
+        echo "USAGE IS GREATER OR EQUAL TO $CRITICAL_USAGE% ==> RUN STRIGIL SCRIPT"
+
+        cd "$STRIGIL_DIR" || {
+            send_email "Script Failure: Directory Change Failed" "Failed to change directory to $STRIGIL_DIR."
+            exit 1
+        }
+
+        # Log strigil.py execution start
+        echo "#######################################################################"
+        echo "STARTING STRIGIL SCRIPT EXECUTION AT $(date)"
+        echo "#######################################################################"
+
+        if ! /bin/python strigil.py; then
+            echo "#######################################################################"
+            echo "STRIGIL SCRIPT FAILED AT $(date)"
+            echo "#######################################################################"
+            send_email "Script Failure: Strigil Execution Failed" "The strigil.py script failed to execute. Please check the logs in $LOG_FILE for more details."
+            exit 1
+        fi
+
+        # Log strigil.py execution end
+        echo "#######################################################################"
+        echo "STRIGIL SCRIPT COMPLETED SUCCESSFULLY AT $(date)"
+        echo "#######################################################################"
+
+        # Retrieve bucket name after strigil.py execution
+        if bucket_name=$(jq -r '.config.bucket' "$CONFIG_FILE"); then
+            echo "Bucket name retrieved successfully: $bucket_name"
+        else
+            send_email "Script Failure: Bucket Name Retrieval Failed" "Failed to retrieve bucket name from $CONFIG_FILE after running strigil.py."
+            exit 1
+        fi
+
+        # Retrieve path name 
+        if path=$(jq -r '.config.project' "$CONFIG_FILE"); then
+            echo "Path name retrieved successfully: $path"
+        else
+            send_email "Script Failure: Path Name Retrieval Failed" "Failed to retrieve path name from $CONFIG_FILE after running strigil.py."
+            exit 1
+        fi
+        END_TIME=$(date)
+        send_email "Script Success" "Script ran successfully.\nStart Time: $START_TIME\nEnd Time: $END_TIME\nBucket: $bucket_name\nPATH: $path\nFROM: $HOSTNAME($HOSTNAME)"
+    else
+        echo "USAGE IS LESS THAN $CRITICAL_USAGE% ==> DO NOTHING"
+    fi
+
+    echo "#######################################################################"
+    echo "CRON JOB ENDED AT $(date)"
+    echo "#######################################################################"
+
+} >> "$LOG_FILE" 2>&1 || {
+    send_email "Script Failure: Unknown Error" "An unknown error occurred while running the script. Check the logs in $LOG_FILE for details."
+    exit 1
+}
